on:
  push:
   branches:
     - master

jobs:
  build-image:
    name: Build and deploy image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.docker_registry }} # default: index.docker.io
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Build from Dockerfile
        id: build-image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.docker_registry }}/cargo:latest
          context: "."